name: P2 Workflow

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile Java Classes
        working-directory: ./Projects/P2
        run: ./gradlew build testClasses -x test

  Test-PacMan-Move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test PacMan.move()
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManMove

  Test-Ghost-Move:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test Ghost.move()
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostMove

  Test-Map-GetLoc:
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      - uses: actions/checkout@v2
      - name: Test Map.getLoc()
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapGetLoc