name: P2 Workflow

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Compile Test Cases
        working-directory: ./Projects/P2
        run: ./gradlew build testClasses -x test

  Test-PacMan-Consume:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Running Test
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestPacManConsume

  Test-Map-EatCookie:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Running Test
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestMapEatCookie
  Test-Ghost-Attack:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Running Test
        working-directory: ./Projects/P2
        run: |
          ./gradlew build testClasses -x test
          ./gradlew test --tests TestGhostAttack
          
  Ghost-is_pacman_in_range:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk:13
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       # Runs a set of commands using the runners shell
       - name: Test is_pacman_in_range()
       - name: Test Ghost-is_pacman_in_range()
         working-directory: ./Projects/P2
         run: |
           ./gradlew build testClasses -x test
           ./gradlew test --tests TestPacManInRange
           
  Pacman-is_ghost_in_range:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     container: openjdk:13
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       # Runs a set of commands using the runners shell
       - name: Test Pacman-is_ghost_in_range()
         working-directory: ./Projects/P2
         run: |
           ./gradlew build testClasses -x test
           ./gradlew test --tests TestGhostInRange
           
  Map-attack:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
     container: openjdk:13
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
       # Runs a set of commands using the runners shell
       - name: Test Map-is_ghost_in_range()
         working-directory: ./Projects/P2
         run: |
           ./gradlew build testClasses -x test
           ./gradlew test --tests TestMapAttack
